[opener]
edit = [
	{ run = "${EDITOR:-vim} %s", desc = "$EDITOR",      for = "unix", block = true },
]
play = [
    { run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
	{ run = "xdg-open %s1",    desc = "Play", for = "linux", orphan = true },
	{ run = "mediainfo %s1; echo 'Press enter to exit'; read _", block = true, desc = "Show media info", for = "unix" },
]

